# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departaments'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Instructor office', 'verbose_name_plural': 'Instructor offices'},
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=4, verbose_name='credits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='university.Student', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='budget',
            field=models.FloatField(verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Departament', verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_of', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.SlugField(verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(height_field=531, upload_to=b'students', verbose_name='Photo', width_field=413),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_of', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
