# Generated by Django 2.2.7 on 2019-11-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20191111_2154'),
        ('university', '0002_auto_20171003_1903'),
    ]

    operations = [
    ]
