# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20171003_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=b'students', verbose_name='Photo'),
        ),
    ]
