# Generated by Django 2.2.7 on 2019-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_merge_20191111_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students', verbose_name='Photo'),
        ),
    ]
